# CSSPVP Configuration

# Lobby settings
lobby:
  prevent-block-break: true
  prevent-block-place: true
  prevent-damage: true
  prevent-player-damage: true
  prevent-hunger: true
  clear-inventory-on-join: true
  op-bypass: true

# Arena settings
arena:
  default-kit: default
  prevent-hunger: false

# Duel settings
duel:
  use-arena-inventory: true
  request-timeout: 60
  countdown: 10

# Random duel settings
random-duel:
  countdown: 5