name: CSSPVP
version: 2.0.5
main: com.copestudios.csspvp.CSSPVP
api-version: 1.21
description: Cope Studios Simple PvP plugin
author: Cope Studios

commands:
  csp:
    description: Main plugin command
    usage: /csp <setlobby|create|setup|gui>
    aliases: [copesp]
  csa:
    description: Arena command
    usage: /csa <join|leave|setkit|kit|list>
    aliases: [copesa]
  csd:
    description: Duel command
    usage: /csd <player|create|setup|accept|leave|stop>
    aliases: [copesd]
  csrd:
    description: Random duel command
    usage: /csrd <arena|start|leave|stop>
    aliases: [copesrd]

permissions:
  csspvp.*:
    description: Grants all CSSPVP permissions
    children:
      csspvp.admin.*: true
      csspvp.user.*: true

  csspvp.admin.*:
    description: Grants all admin permissions
    children:
      csspvp.admin.setlobby: true
      csspvp.admin.create: true
      csspvp.admin.setup: true
      csspvp.admin.gui: true
      csspvp.admin.setkit: true
      csspvp.admin.kit.others: true
      csspvp.admin.create.zone: true
      csspvp.admin.setup.zone: true
      csspvp.admin.duel.stop: true
      csspvp.admin.random-duel: true
      csspvp.admin.random-duel.stop: true
      csspvp.bypass.lobby: true

  csspvp.user.*:
    description: Grants all user permissions
    children:
      csspvp.join: true
      csspvp.leave: true
      csspvp.kit: true
      csspvp.list: true
      csspvp.duel: true
      csspvp.random-duel: true

  csspvp.admin.setlobby:
    description: Allows setting the lobby location
    default: op

  csspvp.admin.create:
    description: Allows creating arenas
    default: op

  csspvp.admin.setup:
    description: Allows setting up arenas
    default: op

  csspvp.admin.gui:
    description: Allows accessing the arena settings GUI
    default: op

  csspvp.admin.setkit:
    description: Allows setting arena kits
    default: op

  csspvp.admin.kit.others:
    description: Allows giving kits to other players
    default: op

  csspvp.admin.create.zone:
    description: Allows creating duel zones
    default: op

  csspvp.admin.setup.zone:
    description: Allows setting up duel zones
    default: op

  csspvp.admin.duel.stop:
    description: Allows stopping duels
    default: op

  csspvp.admin.random-duel:
    description: Allows starting random duels
    default: op

  csspvp.admin.random-duel.stop:
    description: Allows stopping random duels
    default: op

  csspvp.bypass.lobby:
    description: Allows bypassing lobby restrictions
    default: op

  csspvp.join:
    description: Allows joining arenas
    default: true

  csspvp.leave:
    description: Allows leaving arenas
    default: true

  csspvp.kit:
    description: Allows getting arena kits
    default: true

  csspvp.list:
    description: Allows listing arenas
    default: true

  csspvp.duel:
    description: Allows dueling other players
    default: true

  csspvp.random-duel:
    description: Allows participating in random duels
    default: true